export const MOVEMENT = {
  STOP_DISTANCE: 10,
  SNAP_DISTANCE: 3,
  IDLE_SPEED: 3,
  ACCELERATION_MULTIPLIER: 4,
  FRICTION_PER_60FPS_FRAME: 0.96,
  AFTERBURN_MULTIPLIER: 3,
  SERVER_TICK_RATE: 30,
} as const;

export const NETCODE = {
  INTERPOLATION_FACTOR: 0.15,
  SERVER_BUFFER_MS: 100,
} as const;
