// Field registry for the admin console.
//
// Derived FROM THE DRIZZLE SCHEMA, not hand-written. A curated list would be
// wrong the day someone adds a column — and "the admin console can change
// everything" is only true if the list cannot fall behind. Drizzle exposes
// each column's name, SQL type, nullability and default at runtime, so the
// whole registry is generated by reading the table object.
//
// This module is the single authority for:
//   * which columns an admin may write   (writableFields)
//   * which columns nobody may write     (PROTECTED)
//   * how a value is coerced/validated   (coerceValue)
// Both the socket handler and the client editor read from it, so the UI can
// never offer a field the server would reject, and vice versa.
import { schema } from "../db/index.js";

/** "integer" covers every whole-number column (integer/bigint/serial);
 *  "number" is real/float, where fractions are legitimate. */
export type FieldKind = "number" | "integer" | "string" | "boolean" | "json" | "date";

export interface FieldMeta {
  /** Drizzle property name — what the client sends and the server writes. */
  key: string;
  /** Underlying SQL column, for display only. */
  column: string;
  kind: FieldKind;
  notNull: boolean;
  /** Present for varchar; the editor uses it to cap input length. */
  maxLength?: number;
  /** True when writing this field is refused outright. */
  protected: boolean;
  /** Why it is protected — surfaced in the UI so the block is not mysterious. */
  protectedReason?: string;
}

/**
 * Columns an admin console must never write, with the reason.
 *
 * `isAdmin` is the important one: granting staff must not be possible through
 * the same generic form that edits credits, or any compromised/careless admin
 * session silently becomes an account-promotion tool. It is changed by a
 * separate, deliberate action (admin:setAdmin) instead.
 *
 * The identity columns are excluded because rewriting them corrupts rows
 * rather than editing them: `id` is the primary key every other table's
 * foreign keys point at, and `accountId` is the unique login link — pointing
 * two players at one account, or renumbering a player, breaks referential
 * integrity in ways no amount of in-game editing can repair.
 */
export const PROTECTED: Record<string, string> = {
  id: "Primary key — other tables reference it",
  accountId: "Login link — must stay unique per account",
  isAdmin: "Staff flag — use the dedicated Grant/Revoke admin action",
};

function kindOf(col: any): FieldKind {
  // Drizzle's runtime column objects carry dataType/columnType — verified
  // against the live schema: 55 columns, e.g. credits = PgBigInt53/number,
  // skills = PgJsonb/json, lastSeen = PgTimestamp/date, faction = PgVarchar
  // (len 16, nullable).
  //
  // The bigint columns here use { mode: "number" }, so they arrive as real JS
  // numbers rather than strings. They are still split out from plain numbers
  // because they must be whole: they map to 64-bit integer columns, and a
  // fractional credit value would be rejected by the driver.
  const ct = String(col?.columnType ?? "");
  const dt = String(col?.dataType ?? "");
  // Case-insensitive, and covers PgInteger/PgSerial too — not just bigint.
  // The first version tested `ct.includes("Bigint")` against Drizzle's actual
  // "PgBigInt53" (capital I) so it never matched, and integer columns such as
  // level/honor were never caught at all: both accepted 12.7 and handed a
  // fraction to an integer column.
  const ctLower = ct.toLowerCase();
  if (ctLower.includes("bigint") || ctLower.includes("integer") || ctLower.includes("serial")) {
    return "integer";
  }
  if (dt === "number") return "number";
  if (dt === "boolean") return "boolean";
  if (dt === "json") return "json";
  if (dt === "date") return "date";
  return "string";
}

/** Every column of `players`, in schema order, with protection flags. */
export function playerFields(): FieldMeta[] {
  // Symbol.for("drizzle:Columns") is the accessor that actually works on this
  // Drizzle version (probed: 55 columns). `_.columns` is undefined here, so
  // it is deliberately NOT used as a fallback — a silent {} would make the
  // whole registry empty and every admin write fail with "Unknown field".
  const cols = (schema.players as any)[Symbol.for("drizzle:Columns")];
  if (!cols) {
    throw new Error(
      "[admin/fields] Cannot read Drizzle column metadata for `players`. " +
      "The accessor changed with a Drizzle upgrade — fix kindOf/playerFields " +
      "rather than letting the admin console silently lose every field.",
    );
  }
  const out: FieldMeta[] = [];
  for (const [key, col] of Object.entries<any>(cols)) {
    const reason = PROTECTED[key];
    out.push({
      key,
      column: String(col?.name ?? key),
      kind: kindOf(col),
      notNull: Boolean(col?.notNull),
      maxLength: typeof col?.length === "number" ? col.length : undefined,
      protected: Boolean(reason),
      protectedReason: reason,
    });
  }
  return out;
}

/** Fast lookup used by the write path. */
const FIELD_MAP: Map<string, FieldMeta> = new Map(
  playerFields().map((f) => [f.key, f]),
);

export function fieldMeta(key: string): FieldMeta | undefined {
  return FIELD_MAP.get(key);
}

export class FieldError extends Error {}

/**
 * Coerce and validate one incoming value against its column.
 *
 * Throws FieldError on anything the column cannot hold. This matters more
 * than it looks: the client sends JSON, so a number field can arrive as a
 * string, `NaN`, or `Infinity`, and writing those produces either a driver
 * error mid-transaction or a corrupt row. Rejecting here keeps a bad edit
 * from partially applying.
 */
export function coerceValue(key: string, raw: unknown): unknown {
  const f = fieldMeta(key);
  if (!f) throw new FieldError(`Unknown field "${key}"`);
  if (f.protected) throw new FieldError(f.protectedReason ?? "Field is protected");

  if (raw === null) {
    if (f.notNull) throw new FieldError(`${key} cannot be null`);
    return null;
  }

  switch (f.kind) {
    case "number":
    case "integer": {
      const n = typeof raw === "string" ? Number(raw) : raw;
      if (typeof n !== "number" || !Number.isFinite(n)) {
        throw new FieldError(`${key} must be a finite number`);
      }
      // Integer columns silently truncate floats in some drivers and error in
      // others; round here so the behaviour is the same either way.
      return f.kind === "integer" ? Math.round(n) : n;
    }
    case "boolean": {
      if (typeof raw === "boolean") return raw;
      if (raw === "true") return true;
      if (raw === "false") return false;
      throw new FieldError(`${key} must be a boolean`);
    }
    case "string": {
      const s = typeof raw === "string" ? raw : String(raw);
      if (f.maxLength && s.length > f.maxLength) {
        throw new FieldError(`${key} exceeds ${f.maxLength} characters`);
      }
      return s;
    }
    case "date": {
      const d = raw instanceof Date ? raw : new Date(raw as any);
      if (Number.isNaN(d.getTime())) throw new FieldError(`${key} is not a valid date`);
      return d;
    }
    case "json": {
      // The editor sends JSON columns as text so an admin can edit them
      // freely; parse here and let a syntax error surface as a clean message
      // instead of a driver exception.
      if (typeof raw !== "string") return raw;
      try {
        return JSON.parse(raw);
      } catch {
        throw new FieldError(`${key} is not valid JSON`);
      }
    }
  }
}

/** Validate a whole update payload. Returns the coerced object to write. */
export function coerceUpdates(updates: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  for (const [k, v] of Object.entries(updates)) {
    out[k] = coerceValue(k, v);
  }
  if (Object.keys(out).length === 0) throw new FieldError("No fields to update");
  return out;
}
