// Cosmic UI atlas access. Frames are TWO layered textures — a base metal plate
// and a separately-tintable emissive energy channel — both nine-sliced on the
// same margins. This module centralises their paths + slice margins so every
// component builds frames the same way. Generated by
// scripts/cosmic-atlas/gen_frame.py (manifests/frame.json).
import * as PIXI from "pixi.js";

const ROOT = "/assets/ui/cosmic";

export interface NineSliceMargins {
  left: number; top: number; right: number; bottom: number;
}

export interface FrameAtlas {
  base: string;         // metal plate texture URL
  emissive: string;     // white energy channel URL (tint at runtime)
  size: number;
  slice: NineSliceMargins;
}

// Mirrors manifests/frame.json. Kept in sync with the generator's constants.
export const FRAME: FrameAtlas = {
  base: `${ROOT}/textures/frame-base.png`,
  emissive: `${ROOT}/emissive/frame-glow.png`,
  size: 320,
  slice: { left: 54, top: 54, right: 54, bottom: 54 },
};

/** Make a nine-sliced sprite from a texture URL at the frame's margins. Starts
 *  with a blank texture and swaps in the real one once PIXI.Assets loads it
 *  (v8's Texture.from(url) only checks the cache — it no longer implicitly
 *  fetches the way v7 did). */
export function makeNineSlice(url: string, m: NineSliceMargins): PIXI.NineSlicePlane {
  const cached = PIXI.Cache.has(url) ? (PIXI.Cache.get(url) as PIXI.Texture) : PIXI.Texture.EMPTY;
  const plane = new PIXI.NineSlicePlane(cached, m.left, m.top, m.right, m.bottom);
  if (cached === PIXI.Texture.EMPTY) {
    PIXI.Assets.load(url).then((tex: PIXI.Texture) => {
      if (!plane.destroyed) plane.texture = tex;
    });
  }
  return plane;
}
