// Cosmic UI atlas access. Frames are TWO layered textures — a base metal plate
// and a separately-tintable emissive energy channel — both nine-sliced on the
// same margins. This module centralises their paths + slice margins so every
// component builds frames the same way. Generated by
// scripts/cosmic-atlas/gen_frame.py (manifests/frame.json).
import * as PIXI from "pixi.js";

const ROOT = "/assets/ui/cosmic";

export interface NineSliceMargins {
  left: number; top: number; right: number; bottom: number;
}

export interface FrameAtlas {
  base: string;         // metal plate texture URL
  emissive: string;     // white energy channel URL (tint at runtime)
  size: number;
  slice: NineSliceMargins;
}

// Mirrors manifests/frame.json. Kept in sync with the generator's constants.
export const FRAME: FrameAtlas = {
  base: `${ROOT}/textures/frame-base.png`,
  emissive: `${ROOT}/emissive/frame-glow.png`,
  size: 320,
  slice: { left: 54, top: 54, right: 54, bottom: 54 },
};

/** Make a nine-sliced sprite from a texture URL at the frame's margins. */
export function makeNineSlice(url: string, m: NineSliceMargins): PIXI.NineSlicePlane {
  const tex = PIXI.Texture.from(url);
  return new PIXI.NineSlicePlane(tex, m.left, m.top, m.right, m.bottom);
}
